version: '2'
services:
  web:
    image: omarmontoya90/hola_mundo:v1
    ports:
      - "3000:3000"
    volumes:
      - "./:/hola_mundo"
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    depends_on:
      - postgres
    links:
      - postgres:postgres

  postgres:
    image: postgres:9.4
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
